packages:
  - "apps/*"
  - "apps/web/.react-email"
  - "packages/*"
  - "packages/embeds/*"

pnpm:
  onlyBuiltDependencies:
    - "@prisma/client"
    - "@prisma/engines"
    - "@swc/core"
    - "esbuild"
    - "sharp"
    - "sqlite3"
    - "protobufjs"
    - "prisma"
